<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20386" started-at="2022-04-14T05:46:04Z" finished-at="2022-04-14T05:46:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20386" started-at="2022-04-14T05:46:04Z" finished-at="2022-04-14T05:46:24Z">
      <class name="textscript.Testscript_login">
        <test-method status="PASS" signature="open()[pri:0, instance:textscript.Testscript_login@1d057a39]" name="open" is-config="true" duration-ms="11522" started-at="2022-04-14T11:16:04Z" finished-at="2022-04-14T11:16:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open -->
        <test-method status="FAIL" signature="test()[pri:0, instance:textscript.Testscript_login@1d057a39]" name="test" duration-ms="6783" started-at="2022-04-14T11:16:15Z" finished-at="2022-04-14T11:16:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at textscript.Testscript_login.test(Testscript_login.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="close(org.testng.ITestResult)[pri:0, instance:textscript.Testscript_login@1d057a39]" name="close" is-config="true" duration-ms="2046" started-at="2022-04-14T11:16:22Z" finished-at="2022-04-14T11:16:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test status=FAILURE method=Testscript_login.test()[pri:0, instance:textscript.Testscript_login@1d057a39] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- textscript.Testscript_login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
